url: "http://davidlynch.org"
pygments: true
permalink: /blog/:year/:month/:day/:title/
markdown: rdiscount

exclude: ["Rakefile", "Readme.markdown"]

paginate: 10
pagination_roots: ["/blog"]

sitename: "David Lynch"
subtitle: "is not a director"

tag_dir: "blog/tag"
